name: temporal-action-seg
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch>=2.2
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
      - pytorch-lightning>=2.2
      - wandb
      - lmdb
      - numpy
      - matplotlib
      - scikit-learn
      - pyyaml
      - tqdm
